#!/usr/bin/env Rscript
# vi: ft=R

library(methods)

args <- commandArgs(trailingOnly = F)
script.path <- sub("--file=","",args[grep("--file=",args)])

devtools::check(dirname(script.path))

warnings()
