#!/usr/bin/env Rscript
# vi: ft=R
args <- commandArgs(trailingOnly = F)
script.path <- sub("--file=","",args[grep("--file=",args)])
source(file.path(dirname(script.path), 'BiodbFactory.R'), chdir = TRUE)

########
# MAIN #
########

# Create factory
factory <- BiodbFactory$new(useragent = "dbcheck ; pierrick.roger@gmail.com", cache.dir = file.path(dirname(script.path), 'cache'), debug = TRUE)

# Get massbank instance
massbank <- factory$getConn(BIODB.MASSBANK)

# Get massbank entries
massbank.entry.ids <- massbank$getEntryIds(BIODB.SPECTRUM, max.results = 3)
massbank.entries <- factory$createEntry(BIODB.MASSBANK, BIODB.SPECTRUM, id = massbank.entry.ids)

# Get compounds
massbank.compounds <- lapply(massbank.entries, function(x) x$getField(BIODB.COMPOUND))

# Loop on all databases
for (odb in c(BIODB.CHEBI)) {
	id.field <- biodb.get.database.id.field(odb)
	odb.compound.ids <- vapply(massbank.compounds, function(x) x$getFieldValue(id.field, compute = FALSE), FUN.VALUE = '')
	odb.compounds <- factory$createEntry(odb, BIODB.COMPOUND, id = odb.compound.ids)


}
