#!/usr/bin/env Rscript
# vi: ft=R

library(devtools)

args <- commandArgs(trailingOnly = F)
SCRIPT.PATH <- sub("--file=","",args[grep("--file=",args)])
SCRIPT.DIR <- dirname(SCRIPT.PATH)

devtools::test(SCRIPT.DIR)
