@startuml

skinparam classBackgroundColor white
skinparam classArrowColor black
skinparam classBorderColor black
skinparam shadowing false
hide empty members
hide circle

namespace biodb {

	' Classes
	abstract class Object
	class Biodb
	abstract class Conn
	abstract class Entry
	class Factory
	class ChebiConn
	class ChebiEntry
	abstract class Observer
	class Logger
	abstract class Observable

	' Hierarchy
	Object <|-- Biodb
	Object <|-- Conn
	Object <|-- Entry
	Object <|-- Factory
	Conn <|-- ChebiConn
	Entry <|-- ChebiEntry
	Observer <|-- Logger

	' Relations
	Factory "1" *-- "*" Conn
	Biodb "1" *-- "1" Factory
	Biodb "1" *-- "*" Observer
}

@enduml
