#' Extension package class
#'
#' @description
#' A class for generating the skeleton of a new extension package.
#'
#' @details
#' This class manages the files of an extension package.
#'
#' It can generate all the files of a new extension package: DESCRIPTION,
#' NEWS, README.md, tests, definitons.yml, etc. Optionnaly it also generates
#' other files like: a `.travis.yml` file for Travis-CI, a Makefile for easing
#' development on UNIX-like platforms outside of Rstudio.
#'
#' It can also upgrade files of an existing package like: definitions.yml,
#' Makefile, .travis.yml, LICENSE, etc.
#'
#' @import R6
#' @import chk 
#' @include ExtGenerator.R
#' @export
ExtPackage <- R6::R6Class('ExtPackage',

inherit=ExtGenerator,

public=list(
         
#' @description
#' Constructor
#' @param makefile  Set to TRUE if you want a Makefile to be generated.
#' add some special directives inside the Makefile.
#' @return A new instance.
initialize=function(makefile=FALSE, ...) {
    super$initialize(...)
    chk::chk_flag(makefile)
    private$makefile <- makefile
}

#' @description
#' Generates the skeleton for the new extension package.
#'
#' @examples
#' # Create a new package:
#' biodb::ExtPackage$new('/path/to/my/biodbMyNewDb')$generate()
#'
,generate=function() {
    
    private$checkPathDoesNotExist()
    dir.create(private$path)

    ExtDescriptionFile$new(path=private$path, dbName=private$dbName,
                           newPkg=private$newPkg, rcpp=private$rcpp)$generate()
    if (private$makefile)
        ExtMakefile$new(path=private$path, newPkg=private$newPkg)$generate()
    ExtLicense$new(path=private$path)$generate()
    ExtReadme$new(path=private$path, dbName=private$dbName,
                  dbTitle=private$dbTitle)$generate()
    if ( ! is.null(private$dbName)) {
        ExtConnClass$new(path=private$path, dbName=private$dbName,
                         dbTitle=private$dbTitle, connType=private$connType,
                         editable=private$editable, writable=private$writable,
                         remote=private$remote,
                         downloadable=private$downloadable)$generate()
        ExtEntryClass$new(path=private$path, dbName=private$dbName,
                          dbTitle=private$dbTitle,
                          entryType=private$entryType)$generate()
        ExtDefinitions$new(path=private$path, dbName=private$dbName,
                           dbTitle=private$dbTitle, connType=private$connType,
                           entryType=private$entryType, remote=private$remote,
                           downloadable=private$downloadable)$generate()
    }
    ExtPackageFile$new(path=private$path, dbName=private$dbName,
                       rcpp=private$rcpp,
                       vignetteName=private$vignetteName)$generate()
    if (private$rcpp)
        ExtCpp$new(path=private$path)$generate()
    ExtRbuildignore$new(path=private$path)$generate()
    ExtTravisFile$new(path=private$path, pkgName=private$pkgName,
                      email=private$email)$generate()
}

#' @description
#' Upgrade files of (definitions.yml, Makefile, etc) an existing extension
#' package.
#'
#' @examples
#' # Create a new package:
#' biodb::ExtPackage$new('/path/to/my/biodbFooDb')$upgrade()
#'
,upgrade=function() {

    chk::chk_dir(private$path)
    private$checkFilesExist()

    if (private$makefile)
        ExtMakefile$new(path=private$path, newPkg=private$newPkg)$upgrade()
    ExtRbuildignore$new(path=private$path)$upgrade()
}
),

private=list(
    makefile=NULL

,checkFilesExist=function() {
    chk::chk_file(file.path(private$path, 'DESCRIPTION'))
    # NAMESPACE file will be generated by roxygen2.
}

,checkPathDoesNotExist=function() {
    if (dir.exists(private$path))
        stop('A folder already exists at "', private$path, '".')
    if (file.exists(private$path))
        stop('A file already exists at "', private$path, '".')
}
))
