# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Close match PPM
#'
#' Matches peaks between two spectra.
#'
#' @param x        sorted M/Z values (ascending order) of input spectrum (no
#' NA).
#' @param y        sorted M/Z values (ascending order) of reference spectrum
#' (no NA).
#' @param xidx     indices of the M/Z peaks of x, taken from the original
#' spectrum ordered in decreasing intensity values.
#' @param yidx     indices of the M/Z peaks of y, taken from the original
#' spectrum ordered in decreasing intensity values.
#' @param xolength ???
#' @param dppm     ???
#' @param dmz      ???
#' @return  ???
#'
closeMatchPpm <- function(x, y, xidx, yidx, xolength, dppm, dmz) {
    .Call(`_biodb_closeMatchPpm`, x, y, xidx, yidx, xolength, dppm, dmz)
}

